### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by ecriminals** [NULL-Security-Team/social-sniper#2]
Please tell me this code is a joke, everything I see about this code is wrong in every way.

**Comment by SirCryptic** [comment]
> 

why what's the issue ? it works as intended 🤔

**Comment by SirCryptic** [comment]
> Please tell me this code is a joke, everything I see about this code is wrong in every way.

why what's the issue ? it works as intended 🤔, furthermore rather than creating a pointless issue can you make a more detailed issue than the one you have opened ? p.s your more than welcome to re-write or contribute to this, it is 3 years old btw 🤨

**Comment by SirCryptic** [comment]
@ecriminals

**Comment by SirCryptic** [comment]
> > > Please tell me this code is a joke, everything I see about this code is wrong in every way.
> > 
> > 
> > why what's the issue ? it works as intended 🤔, furthermore rather than creating a pointless issue can you make a more detailed issue than the one you have opened ? p.s your more than welcome to re-write or contribute to this, it is 3 years old btw 🤨 @ecriminals
> 
> I will rewrite it for you.

be my guest, i don't see what your issue is as you still have not explained , as said "the tool works as intended" you will have to provide more context on what your issue is with the script itself ?
